### ISSUE TITLE
Failed to build due to Promise library confliction

### ISSUE THREAD

**Issue by timerg** [glennsl/rescript-jest#106]
I failed to compile when I tried to install rescript-jest. The reason is that [ryyppy/promise](https://github.com/ryyppy/rescript-promise) and [aantron/promise](https://github.com/aantron/promise) cannot be used together. And unfortunately, my project is heavily depended on **aantron/promise**.

```
.../node_modules/@glennsl/rescript-jest/lib/ocaml/jest.cmi
  and [myfile].cmi make inconsistent assumptions over interface Promise
```

I am sorry to bring this up but may I suggest that you can follow [this workaround](https://github.com/ryyppy/rescript-promise#in-case-you-are-using-aantronpromise)?

**Comment by glennsl** [comment]
Unfortunately this is more of an application-level workaround, not a library-level workaround. Doing this in a library would first of all be a breaking change for everyone else, of course, but will also just cause more problems for more people down the line when it eventually is adopted into the standard library.

I think `aantron/promise` is a much better library myself, but it seems the rescript team in their infinite shortsightedness has decided otherwise and are intent on breaking anything that falls outside of their narrow field of view yet again. If you're going to keep rescript up-to-date, you'll be forced to deal with this when it's included in the standard library, and chances are it's going to be easier to deal with sooner rather than later.

**Comment by timerg** [comment]
Ok I understand. Thanks for your reply.
